version: '3.9'

services:
  mariadb:
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - my-network
    
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    restart: always
    ports:
      - 443:443
    env_file: .env
    volumes:
    - wordpress-data:/var/www/html
    networks:
      - my-network

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/db
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wp
      o: bind

networks:
  my-network:
    driver: bridge
